{% set name = "dftd3-python" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/awvwgk/simple-dftd3/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 3d775608bf85cd389385a84ea5586ede57215ff9cff646480552ca835a9de9ca

build:
  number: 0
  skip: true  # [osx and (python_impl == 'cpython' and py<38)]
  script:
    - set -ex  # [unix]
    - cd python
    - meson setup _build ${MESON_ARGS:---prefix=${PREFIX} --libdir=lib} --buildtype=release -Dpython_version=${PYTHON}  # [unix]
    - meson setup _build --prefix=%PREFIX% --buildtype=release --pkg-config-path=%PREFIX%\lib\pkgconfig -Dpython_version=%PYTHON%  # [win]
    - meson compile -C _build
    - meson install -C _build --no-rebuild
    - copy %SRC_DIR%\assets\parameters.toml %PREFIX%\lib\site-packages\dftd3  # [win]

requirements:
  build:
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - meson
    - python
    - pkg-config
  host:
    - python
    - cffi
    - pip
    - simple-dftd3
    - libblas  # [unix]
  run:
    - python
    - cffi
    - numpy
    - simple-dftd3


test:
  imports:
    - dftd3
    - dftd3.library
    - dftd3.interface
    - dftd3.parameters
    - dftd3.qcschema
  requires:
    - pytest
    - setuptools
    - qcelemental
    - ase
    - tomli
  commands:
    - pytest --pyargs dftd3 -vv  # [build_platform == target_platform and py<=39]

about:
  home: https://github.com/awvwgk/simple-dftd3/tree/main/python
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: Python API for the DFT-D3 project

extra:
  recipe-maintainers:
    - awvwgk
